version: "3"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
    networks:
      containers_network:
         ipv4_address: 172.16.238.10

  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=regular_agent
    networks:
      containers_network:
         ipv4_address: 172.16.238.20 

  database-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database_dir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: teamcity
    networks:
      containers_network:
         ipv4_address: 172.16.238.30


networks:
  containers_network:
      ipam:
        driver: default
        config:
          - subnet: "172.16.238.0/24"
